# DISCLAIMER: This projects has HARDCODED credentials. This should NEVER be like this in a production environment. It's only like this because it's a LAB, to speed things up.

services:
  postgres:
    image: postgres:16-alpine
    restart: on-failure 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

  backend:
    build: ./backend
    restart: on-failure
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    ports:
      - 8000:5000
    volumes:
      - ./backend:/app 
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:

volumes:
  postgres_data:
