# DISCLAIMER: This projects has HARDCODED credentials. This should NEVER be like this in a production environment. It's only like this because it's a LAB, to speed things up.

services:
  postgres:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres

  backend:
    build: ./backend
    restart: on-failure
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - JWT_SECRET=jumentos-lab-secret
    ports:
      - 8000:5000
    volumes:
      - ./backend:/app 
    depends_on:
      - postgres
    networks:
      - postgres

  web:
    build: ./frontend
    restart: on-failure
    environment:
      - API_TARGET=http://backend:5000
    ports:
      - 80:5173
    volumes:
      - ./frontend:/project
      - /project/node_modules
    depends_on:
      - backend
    networks:
      - postgres

networks:
  postgres:

volumes:
  postgres_data:
